various fixes

diff --git a/manifold/etc/rpm/init.d/manifold-agent b/manifold/etc/rpm/init.d/manifold-agent
--- a/manifold/etc/rpm/init.d/manifold-agent
+++ b/manifold/etc/rpm/init.d/manifold-agent
@@ -31,72 +31,72 @@ runlevel=$(set -- $(runlevel); eval "echo \$$#" )
 
 execute()
 {
-        if [ $# != 2 ]
-        then
-                echo "Usage: print_status COMMAND MESSAGE"
-                exit 1
-        fi
+    if [ $# != 2 ]
+    then
+            echo "Usage: print_status COMMAND MESSAGE"
+            exit 1
+    fi
 
-	echo -n $2"..."
-	logger -t $SYSLOG_PREFIX -p $SYSLOG_FACILITY.notice "N: $2"
-	$1 1>/dev/null 2>/dev/null && success || failure
-	# Maybe redirect error messages ?
-	echo ""
+    echo -n $2"..."
+    logger -t $SYSLOG_PREFIX -p $SYSLOG_FACILITY.notice "N: $2"
+    $1 1>/dev/null 2>/dev/null && success || failure
+    # Maybe redirect error messages ?
+    echo ""
 }
 
 start()
 {
-	execute "$DAEMON $DAEMON_ARGS" "Starting $DESC"
-	RETVAL=$?
-	[ "$RETVAL" = 0 ] && touch $VAR_LOCK_FILE
-	echo
+    execute "$DAEMON $DAEMON_ARGS" "Starting $DESC"
+    RETVAL=$?
+    [ "$RETVAL" = 0 ] && touch $VAR_LOCK_FILE
+    echo
 }
 
 stop()
 {
-	if [ -n "`pidfileofproc $DAEMON`" ] ; then
-		execute "killproc $DAEMON" "Stopping $DESC: $NAME"
-		RETVAL=$?
-		[ "$RETVAL" = 0 ] && rm -f $VAR_LOCK_FILE
-		echo
-	else
-		logger -t $SYSLOG_PREFIX -p $SYSLOG_FACILITY.error "E: Cannot stop $DESC: no pidfile found"
-	fi
-	rm -f $PIDFILE.lock $VAR_LOCK_FILE
+    if [ -n "`pidfileofproc $DAEMON`" ] ; then
+        execute "killproc $DAEMON" "Stopping $DESC: $NAME"
+        RETVAL=$?
+        [ "$RETVAL" = 0 ] && rm -f $VAR_LOCK_FILE
+        echo
+    else
+        logger -t $SYSLOG_PREFIX -p $SYSLOG_FACILITY.error "E: Cannot stop $DESC: no pidfile found"
+    fi
+    rm -f $PIDFILE.lock $VAR_LOCK_FILE
 }
 
 reload()
 {
-	echo -n $"Reloading $NAME: "
-	if [ -n "`pidfileofproc $DAEMON`" ] ; then
-	    killproc $DAEMON -HUP
-	else
-	    failure $"Reloading $NAME"
-	fi
-	RETVAL=$?
-	echo
+    echo -n $"Reloading $NAME: "
+    if [ -n "`pidfileofproc $DAEMON`" ] ; then
+        killproc $DAEMON -HUP
+    else
+        failure $"Reloading $NAME"
+    fi
+    RETVAL=$?
+    echo
 }
 
 case "$1" in
-	start)
-		start
-		;;
-	stop)
-		stop
-		;;
-	restart)
-		stop
-		start
-		;;
-	reload)
-		reload
-		;;
-	status)
-		status $DAEMON
-		RETVAL=$?
-		;;
-	*)
-		echo $"Usage: $SCRIPTNAME {start|stop|restart|reload|status}"
-		RETVAL=1
+    start)
+        start
+        ;;
+    stop)
+        stop
+        ;;
+    restart)
+        stop
+        start
+        ;;
+    reload)
+        reload
+        ;;
+    status)
+        status $DAEMON
+        RETVAL=$?
+        ;;
+    *)
+        echo $"Usage: $SCRIPTNAME {start|stop|restart|reload|status}"
+        RETVAL=1
 esac
 exit $RETVAL
